<?php

namespace ApisFrame\Support\enums;

enum AliyunSmsError
{
    const APIERROR = [
        'isv.SMS_SIGNATURE_SCENE_ILLEGAL' => '签名和模板类型不一致',
        'isv.EXTEND_CODE_ERROR' => '扩展码使用错误，相同的扩展码不可用于多个签名',
        'isv.DOMESTIC_NUMBER_NOT_SUPPORTED' => '国际/港澳台消息模板不支持发送境内号码',
        'isv.DENY_IP_RANGE' => '源IP地址所在的地区被禁用',
        'isv.DAY_LIMIT_CONTROL' => '触发日发送限额',
        'isv.SMS_CONTENT_ILLEGAL' => '短信内容包含禁止发送内容',
        'isv.SMS_SIGN_ILLEGAL' => '签名禁止使用',
        'isp.RAM_PERMISSION_DENY' => 'RAM权限不足',
        'isv.OUT_OF_SERVICE' => '业务停机',
        'isv.PRODUCT_UN_SUBSCRIPT' => '未开通云通信产品的阿里云客户',
        'isv.PRODUCT_UNSUBSCRIBE' => '产品未开通',
        'isv.ACCOUNT_NOT_EXISTS' => '账户不存在',
        'isv.ACCOUNT_ABNORMAL' => '账户异常',
        'isv.SMS_TEMPLATE_ILLEGAL' => '该账号下找不到对应模板',
        'isv.SMS_SIGNATURE_ILLEGAL' => '该账号下找不到对应签名',
        'isv.INVALID_PARAMETERS' => '参数格式不正确',
        'isp.SYSTEM_ERROR' => '系统出现错误，请重新调用',
        'isv.MOBILE_NUMBER_ILLEGAL' => '手机号码格式错误',
        'isv.MOBILE_COUNT_OVER_LIMIT' => '手机号码数量超过限制，最多支持1000条',
        'isv.TEMPLATE_MISSING_PARAMETERS' => '模板变量中存在未赋值变量',
        'isv.BUSINESS_LIMIT_CONTROL' => '触发云通信流控限制',
        'isv.INVALID_JSON_PARAM' => '参数格式错误，请修改为字符串值',
        'isv.BLACK_KEY_CONTROL_LIMIT' => '变量中传入疑似违规信息',
        'isv.PARAM_LENGTH_LIMIT' => '参数超过长度限制',
        'isv.PARAM_NOT_SUPPORT_URL' => '变量不支持传入URL',
        'isv.AMOUNT_NOT_ENOUGH' => '账户余额不足',
        'isv.TEMPLATE_PARAMS_ILLEGAL' => '模板变量里包含非法字符，如emoji表情等',
        'SignatureDoesNotMatch' => '客户端生成的签名与服务端不匹配',
        'InvalidTimeStamp.Expired' => '时间戳或日期已过期',
        'SignatureNonceUsed' => '签名随机数已被使用',
        'InvalidVersion' => 'API版本号错误',
        'InvalidAction.NotFound' => '未找到指定的API，请检查您的URL和方法',
        'isv.SIGN_COUNT_OVER_LIMIT' => '超过单自然日签名申请数量上限',
        'isv.TEMPLATE_COUNT_OVER_LIMIT' => '超过单自然日模板申请数量上限',
        'isv.SIGN_NAME_ILLEGAL' => '签名名称不符合规范',
        'isv.SIGN_FILE_LIMIT' => '签名认证材料附件大小超过限制',
        'isv.SIGN_OVER_LIMIT' => '签名字符数量超过限制',
        'isv.TEMPLATE_OVER_LIMIT' => '模板字符数量超过限制',
        'SIGNATURE_BLACKLIST' => '签名内容涉及违规信息',
        'isv.SHORTURL_OVER_LIMIT' => '超过单自然日短链申请数量上限',
        'isv.NO_AVAILABLE_SHORT_URL' => '该账号无有效短链',
        'isv.SHORTURL_NAME_ILLEGAL' => '短链名不能超过24个字符',
        'isv.SOURCEURL_OVER_LIMIT' => '原始链接字符数量超过限制',
        'isv.SHORTURL_TIME_ILLEGAL' => '短链有效期期限超过限制',
        'isv.PHONENUMBERS_OVER_LIMIT' => '上传手机号个数超过上限',
        'isv.SHORTURL_STILL_AVAILABLE' => '原始链接生成的短链仍在有效期内',
        'isv.ERROR_EMPTY_FILE' => '签名文件为空',
        'isp.GATEWAY_ERROR' => '调用发送应用模块失败',
        'isv.ERROR_SIGN_NOT_DELETE' => '审核中的签名，暂时无法删除',
        'isv.ERROR_SIGN_NOT_MODIFY' => '已通过的签名不支持修改',
        'isv.ERROR_TEMPLATE_NOT_DELETE' => '审核中的模板，暂时无法删除',
        'isv.ERROR_TEMPLATE_NOT_MODIFY' => '已通过的模板不支持修改',
        'isv.SMS_OVER_LIMIT' => '单日最多申请模板或签名100条',
        'isv.CUSTOMER_REFUSED' => '用户已退订推广短信',
        'isv.SMS_TEST_SIGN_TEMPLATE_LIMIT' => '测试模板和签名限制'
    ];
}
